MinuteThreshold = 10
TrainRefreshTime = 30
TrainStationCode = "A02"
DisplayRows = 2
DisplayCols = 17

AbrvStations = {
    "Metro Center": ["Metro Ctr"],
    "Farragut North": ["Farragut N"],
    "Dupont Circle": ["Dupont Cir"],
    "Woodley Park-Zoo/Adams Morgan": ["Woodley Pk"],
    "Cleveland Park": ["Cleve Pk"],
    "Van Ness-UDC": ["Van Ness"],
    "Tenleytown-AU": ["Tenleytown"],
    "Frndshp H": ["Frndshp Ht"],
    "Medical Center": ["Medical Ctr"],
    "Grosvenor-Strathmore": ["Grosvenor"],
    "North Bethesda": ["N Bethesda"],
    "Shady Grove": ["Shady Grv"],
    "Gallery Pl-Chinatown": ["Gallery Pl"],
    "Judiciary Square": ["Judiciary"],
    "Union Station": ["Union Stn"],
    "Rhode Island Ave-Brentwood": ["Rhode Isl"],
    "Brookland-CUA": ["Brookland"],
    "Fort Totten": ["Ft Totten"],
    "Silver Spring": ["Silvr Sprg"],
    "Forest Glen": ["Forest Gln"],
    "NoMa-Gallaudet U": ["NoMa-Gall"],
    "McPherson Square": ["McPherson"],
    "Farragut West": ["Farragut W"],
    "Foggy Bottom-GWU": ["Foggy Bttm"],
    "Arlington Cemetery": ["Arlington"],
    "Pentagon City": ["Pentagon C"],
    "Crystal City": ["Crystal C"],
    "Ronald Reagan Washington National Airport": ["DCA Arprt"],
    "Potomac Yard": ["Potomac Yd"],
    "Braddock Road": ["Braddock Rd"],
    "King St-Old Town": ["King St"],
    "Eisenhower Avenue": ["Eisenhower"],
    "Federal Triangle": ["Fed Tri"],
    "Smithsonian": ["Smithson"],
    "L'Enfant Plaza": ["L'Enfant"],
    "Federal Center SW": ["Fed Ctr SW"],
    "Capitol South": ["Cap South"],
    "Eastern Market": ["Eastern Mkt"],
    "Potomac Ave": ["Potomac Av"],
    "Stadium-Armory": ["Std-Armory"],
    "Minnesota Ave": ["Minn Ave"],
    "New Carrollton": ["N Carrollt"],
    "Mt Vernon Sq 7th St-Convention Center": ["Mt Vernon"],
    "Shaw-Howard U": ["Shaw-HU"],
    "U Street/African-Amer Civil War Memorial/Cardozo": ["U Street"],
    "Columbia Heights": ["Columb Hts"],
    "Georgia Ave-Petworth": ["Georgia Av"],
    "West Hyattsville": ["W Hyatts"],
    "Hyattsville Crossing": ["Hyatts Crs"],
    "College Park-U of Md": ["Coll Park"],
    "Archives-Navy Memorial-Penn Quarter": ["Archives"],
    "Navy Yard-Ballpark": ["Navy Yard"],
    "Congress Heights": ["Cong Hgts"],
    "Southern Avenue": ["Southn Ave"],
    "Naylor Road": ["Naylor Rd"],
    "Branch Ave": ["Branch Ave"],
    "Benning Road": ["Benning Rd"],
    "Capitol Heights": ["Cap Hgts"],
    "Addison Road-Seat Pleasant": ["Addison Rd"],
    "Morgan Boulevard": ["Morgan Blvd"],
    "Downtown Largo": ["Dtn Largo"],
    "Van Dorn Street": ["Van Dorn"],
    "Franconia-Springfield": ["Franconia"],
    "Court House": ["Court Hse"],
    "Virginia Square-GMU": ["Va Sq-GMU"],
    "Ballston-MU": ["Ballston"],
    "East Falls Church": ["E Falls Ch"],
    "West Falls Church": ["W Falls Ch"],
    "Dunn Loring-Merrifield": ["Dunn Lorg"],
    "Vienna/Fairfax-GMU": ["Vienna"],
    "Spring Hill": ["Sprng Hill"],
    "Wiehle-Reston East": ["Wiehle-Rst"],
    "Reston Town Center": ["Reston TC"],
    "Innovation Center": ["Innov Ctr"],
    "Washington Dulles International Airport": ["IAD Arprt"],
    "Loudoun Gateway": ["Loudoun Gt"],
}
