[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7.2.0
    tzapu/WiFiManager@^2.0.17

upload_port = COM3
monitor_port = COM3
